# Generated by Django 4.2.16 on 2024-12-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_note_remove_order_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
