# Generated by Django 4.2.16 on 2024-12-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customers_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.IntegerField(default=0),
        ),
    ]
