# Generated by Django 4.2.16 on 2024-12-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='files/images/Item/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes_desktop_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_tablet_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_mobile_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('is_mobile', models.BooleanField(default=True)),
                ('is_tablet', models.BooleanField(default=True)),
                ('is_desktop', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('ssku', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField(default=0)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.category')),
                ('images', models.ManyToManyField(blank=True, null=True, to='products.image_product')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
