# Generated by Django 4.2.16 on 2024-12-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='files/images_Product/Item/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/images/products/%Y/%m/%d/'),
        ),
    ]
