# Generated by Django 4.2.16 on 2024-12-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_cost_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_option',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active_cart',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active_note',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='note_help',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='note_help_bottom',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='note_help_top',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
