# Generated by Django 4.2.16 on 2024-12-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_default_option_product_is_active_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active_coupon',
            field=models.BooleanField(default=True),
        ),
    ]
