# Generated by Django 4.2.16 on 2024-11-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlyvisit',
            name='declaration',
        ),
        migrations.AlterField(
            model_name='hourlyvisit',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_visits', to='visitors.campaign'),
        ),
        migrations.AlterField(
            model_name='hourlyvisit',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_visits', to='visitors.medium'),
        ),
        migrations.AlterField(
            model_name='hourlyvisit',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_visits', to='visitors.source'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_visits', to='visitors.country'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_visits', to='visitors.device'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_visits', to='visitors.operatingsystem'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='visitors.country')),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='visitors.placedictionary')),
            ],
            options={
                'unique_together': {('place_name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='ProductHourlyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_hourly_visits', to='visitors.campaign')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.date')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_hourly_visits', to='visitors.hour')),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_hourly_visits', to='visitors.medium')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_hourly_visits', to='visitors.source')),
                ('user_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_hourly_visits', to='visitors.uservisit')),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='visitors.state'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
