# Generated by Django 4.2.16 on 2024-11-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_remove_hourlyvisit_declaration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='region',
            new_name='state',
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('place_name', 'state')},
        ),
    ]
