# Generated by Django 4.2.16 on 2024-11-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_rename_region_city_state_alter_city_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservisit',
            name='user_agent',
        ),
    ]
