# Generated by Django 4.2.16 on 2024-11-03 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_remove_uservisit_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='visitors.placedictionary')),
            ],
        ),
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Browser', to='visitors.browserdictionary')),
            ],
        ),
        migrations.AddField(
            model_name='uservisit',
            name='browser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_visits', to='visitors.browser'),
        ),
        migrations.AddField(
            model_name='uservisit',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_visits', to='visitors.region'),
        ),
    ]
