# Generated by Django 4.2.16 on 2024-11-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_browserdictionary_region_browser_uservisit_browser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Declaration',
        ),
        migrations.AlterField(
            model_name='browser',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='BrowserDictionary',
        ),
    ]
