# Generated by Django 4.2.16 on 2024-11-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_delete_declaration_alter_browser_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
