# Generated by Django 4.2.16 on 2024-12-02 08:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes_desktop_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_tablet_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_mobile_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('is_mobile', models.BooleanField(default=True)),
                ('is_tablet', models.BooleanField(default=True)),
                ('is_desktop', models.BooleanField(default=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FooterModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes_desktop_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_tablet_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_mobile_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('is_mobile', models.BooleanField(default=True)),
                ('is_tablet', models.BooleanField(default=True)),
                ('is_desktop', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('copyright_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes_desktop_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_tablet_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_mobile_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('is_mobile', models.BooleanField(default=True)),
                ('is_tablet', models.BooleanField(default=True)),
                ('is_desktop', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='SliderModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes_desktop_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_tablet_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_mobile_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('is_mobile', models.BooleanField(default=True)),
                ('is_tablet', models.BooleanField(default=True)),
                ('is_desktop', models.BooleanField(default=True)),
                ('images', models.ImageField(upload_to='sliders/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mobile_order', models.PositiveIntegerField(default=0)),
                ('tablet_order', models.PositiveIntegerField(default=0)),
                ('desktop_order', models.PositiveIntegerField(default=0)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to='content.page')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('header', 'Header'), ('slider', 'Slider'), ('content', 'Content'), ('product', 'Product'), ('footer', 'Footer')], default='header', max_length=20)),
                ('mobile_order', models.PositiveIntegerField(default=0)),
                ('tablet_order', models.PositiveIntegerField(default=0)),
                ('desktop_order', models.PositiveIntegerField(default=0)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='content.contentmodule')),
                ('footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='content.footermodule')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='content.headermodule')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='products.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.section')),
                ('slider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='content.slidermodule')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='content.page')),
            ],
        ),
        migrations.AddField(
            model_name='headermodule',
            name='menu_items',
            field=models.ManyToManyField(related_name='headers', to='content.menuitem'),
        ),
        migrations.AddField(
            model_name='footermodule',
            name='social_links',
            field=models.ManyToManyField(related_name='footers', to='content.sociallink'),
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactUs', to='content.page')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='content.page')),
            ],
        ),
    ]
