# Generated by Django 4.2.16 on 2024-12-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_settings', to='content.page')),
                ('contactUs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactUs_settings', to='content.page')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_settings', to='content.page')),
                ('privacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='content.page')),
            ],
        ),
    ]
