# Generated by Django 4.2.16 on 2024-12-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='currency_ar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='currency_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_settings', to='content.page'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='contactUs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactUs_settings', to='content.page'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_settings', to='content.page'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='privacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='content.page'),
        ),
    ]
