# Generated by Django 4.2.16 on 2024-12-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_settings_currency_ar_settings_currency_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=350)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Link', to='content.page')),
            ],
        ),
    ]
