# Generated by Django 4.2.16 on 2024-12-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_browserdictionary'),
        ('content', '0004_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='link',
        ),
        migrations.AddField(
            model_name='links',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Link', to='visitors.campaign'),
        ),
        migrations.AddField(
            model_name='links',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Link', to='visitors.medium'),
        ),
        migrations.AddField(
            model_name='links',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Link', to='visitors.source'),
        ),
    ]
