# Generated by Django 4.2.16 on 2024-12-20 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_links_link_links_campaign_links_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='page',
        ),
        migrations.RemoveField(
            model_name='home',
            name='page',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='page',
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
    ]
